name: user_repository
description: Dart Package Which Manage This User
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
